config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  root 'users/home#top'

  scope module: :users do
  	get 'users/destroy_page'
  	resources :users, only: [:index, :show, :edit, :update], shallow: true do
      resources :relationships, only: [:create, :destroy]
    end
  	resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy], shallow: true do
  		resources :comments, only: [:create, :destroy]
  		resources :likes, only: [:create, :destroy]
  	end
    get 'search' => 'posts#search'
  end

  namespace :admins do
  	resources :users, only: [:index, :destroy]
  	resources :posts, only: [:index, :show, :destroy]
    resources :categories, only: [:new, :create, :update, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord

	validates :title, presence: true
	validates :body, presence: true
	validates :category_id, presence: true

	has_many :comments, dependent: :destroy
	has_many :likes, dependent: :destroy
	has_many :post_images, dependent: :destroy
	belongs_to :user
	belongs_to :category

	accepts_attachments_for :post_images, attachment: :image

	def liked_by?(user)
		likes.where(user_id: user.id).exists?
	end

  def self.ranking
    joins(:likes).group(:post_id).order('count(post_id) desc')
  end

	def self.search(keyword, address, category)
		if category == ""
			where(["title like? OR body like?", "%#{keyword}%", "%#{keyword}%"]).where("address like?", "%#{address}%")
		else
			where(category_id: category).where(["title like? OR body like?", "%#{keyword}%", "%#{keyword}%"]).where("address like?", "%#{address}%")
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :name, length: { maximum: 20 }
  validates :email, presence: true

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id, dependent: :destroy
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :following

  attachment :profile_image
  attachment :cover_image

  def followed_by?(user)
    passive_relationships.where(following_id: user.id).exists?
  end

  def self.ranking
    joins(:passive_relationships).group(:follower_id).order('count(follower_id) desc')
  end
end

app/controllers/admins/posts_controller.rb
class Admins::PostsController < ApplicationController
	before_action :authenticate_admin!
	def index
		@posts = Post.page(params[:page]).per(10)
	end

	def show
		@post = Post.find(params[:id])
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		if params[:com] == "local"
			redirect_to admins_posts_path
		end
	end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
	before_action :authenticate_admin!
	def index
		@users = User.page(params[:page]).per(10)
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
	end
end

app/controllers/users/comments_controller.rb
class Users::CommentsController < ApplicationController
	before_action :authenticate_user!
	def create
		comment = Comment.new(comment_params)
		comment.user_id = current_user.id
		comment.post_id = params[:post_id]
		comment.save
		@post = comment.post
	end

	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
	end

	private

	def comment_params
		params.require(:comment).permit(:body)
	end
end

app/controllers/users/home_controller.rb
class Users::HomeController < ApplicationController
  def top
  	@posts = Post.includes(:post_images, :likes).limit(9).order(created_at: :desc)
  	@post_ranks = Post.ranking.limit(5)
  	@users = User.ranking.limit(5)
  end
end

app/controllers/users/likes_controller.rb
class Users::LikesController < ApplicationController
	before_action :authenticate_user!
	def create
		like = Like.new(user_id: current_user.id, post_id: params[:post_id])
		@post = like.post
		like.save
	end

	def destroy
		like = Like.find(params[:id])
		@post = like.post
		like.destroy
	end
end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :ensure_correct_user, only: [:edit]

  def index
    @posts = Post.includes(:post_images, :likes).page(params[:page]).order(created_at: :desc)
    @category_form = ""
    @sort = "新着順"
  end

  def new
  	@post = Post.new
  end
  
  def create
  	@post = Post.new(post_params)
  	@post.user_id = current_user.id
  	if @post.save
  		redirect_to post_path(@post)
    else
      render "new"  
  	end
  end

  def show
    @post = Post.includes(comments: :user).find(params[:id])
    @comment = Comment.new
    @relation = Post.where(category: @post.category).where.not(id: @post).includes(:post_images, :likes).limit(9)
    address = @post.address
    @map = Geocoder.coordinates(address)
  end

  def edit
  	@post = Post.find(params[:id])
  end

  def update
  	@post = Post.find(params[:id])
  	if @post.update(post_params)
  		redirect_to post_path(@post)
    else
      render "edit"  
  	end
  end

  def destroy
  	post = Post.find(params[:id])
  	post.destroy
  	redirect_to posts_path
  end

  def search
    if params[:sort] == "新着順"
      @posts = Post.includes(:post_images, :likes).search(params[:keyword], params[:address], params[:category]).page(params[:page]).order(created_at: :desc)
    else
      result = Post.includes(:post_images).search(params[:keyword], params[:address], params[:category])
      @posts = result.ranking.page(params[:page])
    end
    @keyword_form = params[:keyword]
    @address_form = params[:address]
    @category_form = params[:category]
    @sort = params[:sort]
    render "index"
  end

  private

  def post_params
  	params.require(:post).permit(:title, :body, :post_code, :address, :category_id, post_images_images: [])
  end

  def ensure_correct_user
    post = Post.find(params[:id])
    if current_user != post.user
      redirect_to posts_path
    end
  end
end

app/controllers/users/relationships_controller.rb
class Users::RelationshipsController < ApplicationController
	before_action :authenticate_user!
	def create
		relationship = Relationship.new(following_id: current_user.id, follower_id: params[:user_id])
		@user = relationship.follower
		relationship.save
	end

	def destroy
		relationship = Relationship.find(params[:id])
		@user = relationship.follower
		relationship.destroy
	end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy_page]
  before_action :ensure_correct_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    if params[:tab] == "いいね"
      @posts = @user.like_posts.includes(:post_images, :likes).page(params[:page]).order(created_at: :desc)
      @tab = "いいね"
    elsif params[:tab] == "フォロー"
      @users = @user.followings.includes(:followings, :followers).page(params[:page])
      @tab = "フォロー"
    elsif params[:tab] == "フォロワー"
      @users = @user.followers.includes(:followings, :followers).page(params[:page])
      @tab = "フォロワー"
    else
      @posts = @user.posts.includes(:post_images, :likes).page(params[:page]).order(created_at: :desc)
      @tab = "記事一覧"
    end
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user)
  	else
  		render "edit"
  	end
  end

  def destroy_page
    
  end

  private

  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image, :email, :cover_image)
  end

  def ensure_correct_user
    if current_user.id != params[:id].to_i
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/home_helper.rb
module User::HomeHelper
end

app/helpers/user/likes_helper.rb
module User::LikesHelper
end

app/helpers/user/posts_helper.rb
module User::PostsHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/helpers/users/relationships_helper.rb
module Users::RelationshipsHelper
end

app/views/users/posts/_comment.html.erb
<tr>
	<td rowspan="2" class="profile-image-td position-top">
		<%= link_to user_path(comment.user) do %>
			<%= attachment_image_tag comment.user, :profile_image, :fill, 80, 80, size: "40x40", format: "jpeg", fallback: "no_image.jpg", class: "comment-profile-image" %>
		<% end %>
	</td>
	<td>
		<span style="display: block;"><%= comment.user.name %></span>
		<span style="font-size: 10px; color: gray;"><%= comment.created_at.to_s(:datetime) %></span>
	</td>
	<td style="padding: 22px 0 0 0;" align="right">
		<% if current_user == comment.user || admin_signed_in? %>
			<%= link_to "削除", comment_path(comment), method: :delete, remote: true, class: "btn btn-sm btn-danger" %>
		<% end %>
	</td>
</tr>
<tr>
	<td colspan="2" style="padding-top: 0;"><%= simple_format(comment.body) %></td>
</tr>

app/views/users/posts/_comments.html.erb
<table class="table" id="comments">
	<% post.comments.each do |comment| %>
		<tbody id="comment-<%= comment.id %>">

			<%= render "users/posts/comment", comment: comment %>

		</tbody>
	<% end %>
</table>

app/views/users/posts/_like.html.erb
<% if user_signed_in? %>
  <% if post.likes.any?{ |like| like.user_id == current_user.id } %>
    <% like = Like.find_by(user_id: current_user.id, post_id: post.id) %>
    <%= link_to like_path(like), method: :delete, remote: true do %>
      <span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;">
    <% end %>
  <% else %>
    <%= link_to post_likes_path(post), method: :post, remote: true do %>
      <span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: gray;">
    <% end %>
  <% end %>
  <span><%= post.likes.size %></span>
  <span style="margin-left: 12px;"><%= post.created_at.to_s(:datetime) %></span>
<% else %>
  <%= link_to new_user_session_path do %>
    <span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;">
  <% end %>
  <span><%= post.likes.size %></span>
  <span style="margin-left: 12px;"><%= post.created_at.to_s(:datetime) %></span>
<% end %>

app/views/users/posts/edit.html.erb
<div class="edit-post shadow">

	<%= form_with model: @post, local: true do |f| %>

		<div class="text-field">

		<% if @post.errors.any? %>
			<% @post.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		<% end %>

			<%= f.attachment_field :post_images_images, multiple: true, id: "file" %>
			<%= f.collection_select :category_id, Category.all, :id, :name, { include_blank: "--ジャンルを選択してください--",}, { class: "category-field form-control" } %>
			<%= f.text_field :title, class: "title-field form-control", placeholder: "タイトル" %>
			<%= f.text_area :body, class: "body-field form-control", placeholder: "本文" %>
			<%= f.text_field :post_code, class: "post-code-field form-control", placeholder: "郵便番号", id: "address_zipcode" %>
			<%= f.text_field :address, class: "address-field form-control", placeholder: "住所", id: "address" %>
			<div class="text-right">
				<%= f.submit "編集", class: "btn btn-primary" %>
			</div>
		</div>
	<% end %>
</div>

app/views/users/posts/edit_prev.html.erb
<div class="post-content shadow">
	<div class="post-image">
		<div id="slider">
			<% @post.post_images.each do |post_image| %>
				<%= attachment_image_tag post_image, :image, :fill, 1200, 800, format: "jpeg", class: "image" %>
			<% end %>
		</div>
	</div>
	<div class="post-text">
		<h4><%= @post.title %></h4>
		<p><%= @post.address %></p>
		<div class="post-body">
			<%= simple_format(@post.body) %>
		</div>

		<h4><%= @post.address %></h4>
		<div id="map" style="height: 300px; background-image: url(<%= asset_path "no_map_img.jpg" %>); background-size: cover;"></div>

		<%= form_with model: @post, local: true do |f| %>
			<%= f.hidden_field :post_images_images, :value => @post.post_images %>
			<%= f.hidden_field :title, :value => @post.title %>
			<%= f.hidden_field :body, :value => @post.body %>
			<%= f.hidden_field :post_code, :value => @post.post_code %>
			<%= f.hidden_field :address, :value => @post.address %>
			<%= f.submit "編集" %>
		<% end %>
	</div>
</div>


<% if @map != nil %>
	<script>
	function initMap(){
	  var pos = {lat: <%= @map[0] %>, lng: <%= @map[1] %>};

	  var map = new google.maps.Map(document.getElementById('map'), {
	  	center: pos,
	  	zoom: 15
	  });

	  var infowindow = new google.maps.InfoWindow({
	  	content: "<%= @post.address %>"
	  });

	  var marker = new google.maps.Marker({
	    position: pos,
	    map: map,
	    title: "<%= @post.address %>"
	　});

	  marker.addListener('click', function() {
	    infowindow.open(map, marker);
	  });
	}

	</script>
	<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV.fetch("API_KEY") %>&callback=initMap" async defer></script>
<% end %>

app/views/users/posts/index.html.erb
<div class="main-content">
	<div class="search-form-1">
		<table class="table">
			<%= form_with url: search_path, method: :get, local: true do |f| %>
				<tr>
					<td><%= f.label :keyword, "キーワード" %></td>
					<td colspan="2"><%= f.text_field :keyword, value: @keyword_form, class: "form-control" %></td>
				</tr>
				<tr>
					<td><%= f.label :address, "住所または地名" %></td>
					<td colspan="4"><%= f.text_field :address, value: @address_form, class: "form-control" %></td>
				</tr>
				<tr>
					<td><%= f.label :category, "ジャンル" %></td>
					<td><%= f.collection_select :category, Category.all, :id, :name, { include_blank: "--ジャンル--", selected: @category_form}, { class: "form-control" } %></td>

				<% if @sort == "新着順" %>
					<td style="text-align: right;">
						<%= f.radio_button :sort, "新着順", checked: true %>
						<%= f.label :sort_新着順, "新着順" %>
					</td>
					<td style="text-align: right;">
						<%= f.radio_button :sort, "いいね順" %>
						<%= f.label :sort_いいね順, "いいね順" %>
					</td>

				<% else %>
					<td style="text-align: right;">
						<%= f.radio_button :sort, "新着順" %>
						<%= f.label :sort_新着順, "新着順" %>
					</td>
					<td style="text-align: right;">
						<%= f.radio_button :sort, "いいね順", checked: true %>
						<%= f.label :sort_いいね順, "いいね順" %>
					</td>
				
				<% end %>
					<td style="text-align: right;"><%= f.submit "検索", class: "btn btn-primary" %></td>
				</tr>
			<% end %>
		</table>
	</div>
	<div class="search-form-2">
		<table class="table">
			<%= form_with url: search_path, method: :get, local: true do |f| %>
				<tr>
					<td colspan="3"><%= f.text_field :keyword, value: @keyword_form, placeholder: "キーワード", class: "form-control" %></td>
				</tr>
				<tr>
					<td colspan="3"><%= f.text_field :address, value: @address_form, placeholder: "住所または地名", class: "form-control" %></td>
				</tr>
				<tr>
					<td colspan="3"><%= f.collection_select :category, Category.all, :id, :name, { include_blank: "--ジャンル--", selected: @category_form}, { class: "form-control" } %></td>
				</tr>
				<tr>
				<% if @sort == "新着順" %>
					<td>
						<%= f.radio_button :sort, "新着順", checked: true %>
						<%= f.label :sort_新着順, "新着順" %>
					</td>
					<td>
						<%= f.radio_button :sort, "いいね順" %>
						<%= f.label :sort_いいね順, "いいね順" %>
					</td>

				<% else %>
					<td>
						<%= f.radio_button :sort, "新着順" %>
						<%= f.label :sort_新着順, "新着順" %>
					</td>
					<td>
						<%= f.radio_button :sort, "いいね順", checked: true %>
						<%= f.label :sort_いいね順, "いいね順" %>
					</td>
				
				<% end %>
					<td align="right"><%= f.submit "検索", class: "btn btn-primary" %></td>
				</tr>
			<% end %>
		</table>
	</div>
	<div class="row">
		<% @posts.each do |post| %>
			<div class="col-sm-4">
				<%= link_to post_path(post) do %>
					<div class="post-item shadow">
						<div class="post-image">
							<%= attachment_image_tag post.post_images[0], :image, :fill, 1050, 630, format: "jpeg", class: "image" %>
						</div>
						<div class="detail">
							<p class="limit2"><%= post.title %></p>
							<div class="post-footer" id="like-<%= post.id %>">

								<%= render "users/posts/like", post: post %>

							</div>
						</div>
					</div>
				<% end %>
			</div>
		<% end %>
	</div>
	<div class="pagenation" align="center">
		<%= paginate @posts, class: "paginate" %>
	</div>
</div>

app/views/users/posts/new.html.erb
<div class="new-post shadow">

	<%= form_with model: @post, local: true do |f| %>

		<div class="text-field">

		<% if @post.errors.any? %>
			<% @post.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		<% end %>

			<%= f.attachment_field :post_images_images, multiple: true, id: "file" %>
			<%= f.collection_select :category_id, Category.all, :id, :name, { include_blank: "--ジャンルを選択してください--",}, { class: "category-field form-control" } %>
			<%= f.text_field :title, class: "title-field form-control", placeholder: "タイトル" %>
			<%= f.text_area :body, class: "body-field form-control", placeholder: "本文" %>
			<%= f.text_field :post_code, class: "post-code-field form-control", placeholder: "郵便番号", id: "address_zipcode" %>
			<%= f.text_field :address, class: "address-field form-control", placeholder: "住所", id: "address" %>
			<div class="text-right">
				<%= f.submit "投稿", class: "btn btn-primary" %>
			</div>
		</div>
	<% end %>
</div>

app/views/users/posts/show.html.erb
<div class="post-content shadow">
	<div class="post-image">
		<div id="slider1">
			<% @post.post_images.each do |post_image| %>
				<div class="slider-item">
					<%= attachment_image_tag post_image, :image, :fill, 1200, 800, format: "jpeg", class: "image" %>
				</div>
			<% end %>
		</div>
	</div>
	<div class="post-text">
		<h4><%= @post.title %></h4>
		<span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span>
		<span><%= @post.likes.size %></span>
		<span style="margin-left: 8px;"><%= @post.created_at.to_s(:datetime) %></span>
		<% if @post.user == current_user %>
			<div class="edit-destroy-button" align="right">
				<%= link_to "編集", edit_post_path(@post), class: "btn btn-primary" %>
				<%= link_to "削除", post_path(@post), method: :delete, data: { confirm: "削除しますか？" }, class: "btn btn-danger" %>
			</div>
		<% end %>
		<div class="post-body">
			<%= simple_format(@post.body) %>
		</div>

		<h5><%= @post.address %></h5>
		<div id="map" style="height: 300px; background-image: url(<%= asset_path "no_map_img.jpg" %>); background-size: cover;"></div>

		<div class="post-content-footer" id="like-<%= @post.id %>">

			<%= render "users/posts/like", post: @post %>

		</div>
		<div class="creater-detail">
			<table class="table">
				<tr>
					<td rowspan="3" class="profile-image-td position-top">
						<%= link_to user_path(@post.user) do %>
							<%= attachment_image_tag @post.user, :profile_image, :fill, 160, 160, size: "80x80", format: "jpeg", fallback: "no_image.jpg", class: "profile-image" %>
						<% end %>
					</td>
					<td colspan="2"><%= @post.user.name %></td>
					<td id="follow-<%= @post.user.id %>" class="text-right">

						<%= render "users/users/follow", user: @post.user %>

					</td>
				</tr>
				<tr>
					<td colspan="3"><%= simple_format(@post.user.introduction) %></td>
				</tr>
				<tr>
					<td>フォロー　<%= @post.user.followings.size %></td>
					<td colspan="2">フォロワー　<%= @post.user.followers.size %></td>
				</tr>
			</table>
		</div>
		<p class="relation-title">関連記事　"<%= @post.category.name %>"</p>
		<div id="slider2">
			<% @relation.each do |post| %>
				<div class="slider-item">
					<%= link_to post_path(post) do %>
						<div class="related-post">
							<div class="post-image">
								<%= attachment_image_tag post.post_images[0], :image, :fill, 690, 420, format: "jpeg"%>
							</div>
							<div class="detail">
								<small class="limit2"><%= post.title %></small>
								<div class="post-footer" id="like-<%= post.id %>">
									<small class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></small>
									<small><%= post.likes.size %></small>
									<small style="margin-left: 8px;"><%= post.created_at.to_s(:datetime) %></small>
								</div>
							</div>
						</div>
					<% end %>
				</div>
			<% end %>
		</div>
	</div>
</div>

<div class="comment shadow">
	<p>コメント <%= @post.comments.size %>件</p>

	<%= render "users/posts/comments", post: @post %>

	<div class="comment-form" align="right">
		<% if user_signed_in? %>
			<%= form_with model: [@post, @comment] do |f| %>
				<%= f.text_area :body, class: "form-control", id: "comment-form-body" %>
				<%= f.submit "コメントする", class: "btn btn-sm btn-primary" %>
			<% end %>
		<% else %>
			<%= image_tag "comment.jpg", alt: "サブタイトル", width: "100%" %>
			<%= link_to "コメントする", new_user_session_path, class: "btn btn-sm btn-primary", style: "margin-top: 10px;" %>
		<% end %>
	</div>
</div>

<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

<% if @map != nil %>
	<script>
	function initMap(){
	  var pos = {lat: <%= @map[0] %>, lng: <%= @map[1] %>};

	  var map = new google.maps.Map(document.getElementById('map'), {
	  	center: pos,
	  	zoom: 15
	  });

	  var infowindow = new google.maps.InfoWindow({
	  	content: "<%= @post.address %>"
	  });

	  var marker = new google.maps.Marker({
	    position: pos,
	    map: map,
	    title: "<%= @post.address %>"
	　});

	  marker.addListener('click', function() {
	    infowindow.open(map, marker);
	  });
	}

	</script>
	<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV.fetch("API_KEY") %>&callback=initMap" async defer></script>
<% end %>