config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  root 'users/home#top'

  scope module: :users do
  	get 'users/destroy_page'
  	resources :users, only: [:index, :show, :edit, :update], shallow: true do
      resources :relationships, only: [:create, :destroy]
    end
  	resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy], shallow: true do
  		resources :comments, only: [:create, :destroy]
  		resources :likes, only: [:create, :destroy]
  	end
    get 'search' => 'posts#search'
  end

  namespace :admins do
  	resources :users, only: [:index, :destroy]
  	resources :posts, only: [:index, :show, :destroy]
    resources :categories, only: [:new, :create, :update, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord

	validates :title, presence: true
	validates :body, presence: true
	validates :category_id, presence: true

	has_many :comments, dependent: :destroy
	has_many :likes, dependent: :destroy
	has_many :post_images, dependent: :destroy
	belongs_to :user
	belongs_to :category

	accepts_attachments_for :post_images, attachment: :image

	def liked_by?(user)
		likes.where(user_id: user.id).exists?
	end

  def self.ranking
    joins(:likes).group(:post_id).order('count(post_id) desc')
  end

	def self.search(keyword, address, category)
		if category == ""
			where(["title like? OR body like?", "%#{keyword}%", "%#{keyword}%"]).where("address like?", "%#{address}%")
		else
			where(category_id: category).where(["title like? OR body like?", "%#{keyword}%", "%#{keyword}%"]).where("address like?", "%#{address}%")
		end
	end
end

app/controllers/admins/posts_controller.rb
class Admins::PostsController < ApplicationController
	before_action :authenticate_admin!
	def index
		@posts = Post.page(params[:page]).per(10)
	end

	def show
		@post = Post.find(params[:id])
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		if params[:com] == "local"
			redirect_to admins_posts_path
		end
	end
end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :ensure_correct_user, only: [:edit]

  def index
    @posts = Post.includes(:post_images, :likes).page(params[:page]).order(created_at: :desc)
    @category_form = ""
    @sort = "新着順"
  end

  def new
  	@post = Post.new
  end
  
  def create
  	@post = Post.new(post_params)
  	@post.user_id = current_user.id
  	if @post.save
  		redirect_to post_path(@post)
    else
      render "new"  
  	end
  end

  def show
    @post = Post.includes(comments: :user).find(params[:id])
    @comment = Comment.new
    @relation = Post.where(category: @post.category).where.not(id: @post).includes(:post_images, :likes).limit(9)
    address = @post.address
    @map = Geocoder.coordinates(address)
  end

  def edit
  	@post = Post.find(params[:id])
  end

  def update
  	@post = Post.find(params[:id])
  	if @post.update(post_params)
  		redirect_to post_path(@post)
    else
      render "edit"  
  	end
  end

  def destroy
  	post = Post.find(params[:id])
  	post.destroy
  	redirect_to posts_path
  end

  def search
    if params[:sort] == "新着順"
      @posts = Post.includes(:post_images, :likes).search(params[:keyword], params[:address], params[:category]).page(params[:page]).order(created_at: :desc)
    else
      result = Post.includes(:post_images).search(params[:keyword], params[:address], params[:category])
      @posts = result.ranking.page(params[:page])
    end
    @keyword_form = params[:keyword]
    @address_form = params[:address]
    @category_form = params[:category]
    @sort = params[:sort]
    render "index"
  end

  private

  def post_params
  	params.require(:post).permit(:title, :body, :post_code, :address, :category_id, post_images_images: [])
  end

  def ensure_correct_user
    post = Post.find(params[:id])
    if current_user != post.user
      redirect_to posts_path
    end
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/user/posts_helper.rb
module User::PostsHelper
end

app/views/admins/posts/_post.html.erb
<table class="admin-post-item table" style="max-width: 800px; border: 1px solid gray; background-color: white;">
		<tr>
			<td rowspan="2" style="width: 150px; padding: 0;">
				<%= link_to admins_post_path(post) do %>
					<%= attachment_image_tag post, :image, :fill, 95, 72, format: "jpeg", fallback: "no_image.jpg", size: "95x72" %>
				<% end %>
			</td>
			<td colspan="2"><%= link_to post.title, admins_post_path(post) %></td>
			<td rowspan="2" style="width: 85px; vertical-align: middle;">
				<%= link_to "削除", admins_post_path(post), method: :delete, remote: true, class: "btn btn-danger" %>
			</td>
		</tr>
		<tr>
			<td>いいね<span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"><%= post.likes.count %></td>
			<td>コメント　<%= post.comments.count %></td>
		</tr>
</table>

app/views/admins/posts/destroy.js.erb
$("#post-<%= @post.id %>").remove()

app/views/admins/posts/index.html.erb
<div class="post-list">
	<% @posts.each do |post| %>
		<div id="post-<%= post.id %>">

			<%= render "admins/posts/post", post: post %>

		</div>
	<% end %>
</div>

app/views/admins/posts/show.html.erb
<div class="admin-post">
	<div class="post-image">
		<%= attachment_image_tag @post, :image, :fill, 600, 400, format: "jpeg" %>
	</div>
	<div class="admin-post-detail">
		<h4><%= @post.title %></h4>
		<span>
			<span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span>
			<%= @post.likes.count %>
			　<%= @post.created_at.to_s(:datetime) %>
		</span>
		<div class="admin-tag-list">
			<% @post.tag_list.each do |tag| %>
				<span class="badge badge-default"><%= tag %></span>
			<% end %>
		</div>
		<p><%= @post.address %></p>
		<div class="admin-post-destroy" align="right">
			<%= link_to "削除", admins_post_path(id: @post.id, com: "local"), method: :delete, class: "btn btn-danger" %>
		</div>
		<div class="admin-post-body">
			<%= simple_format(@post.body) %>
		</div>
		<div class="admin-post-footer" id="like-<%= @post.id %>">
			<span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span>
			<%= @post.likes.count %>
			　<%= @post.created_at.to_s(:datetime) %>
		</div>
		<div class="admin-creater-detail">
			<table class="table">
				<tr>
					<td rowspan="3">
						<%= attachment_image_tag @post.user, :profile_image, :fill, 80, 80, format: "jpeg", fallback: "no_image.jpg" %>
					</td>
					<td colspan="3"><%= @post.user.name %></td>
				</tr>
				<tr>
					<td colspan="3"><%= simple_format(@post.user.introduction) %></td>
				</tr>
				<tr>
					<td style="max-width: 120px;">フォロー　<%= @post.user.followings.count %></td>
					<td>フォロワー　<%= @post.user.followers.count %></td>
					<td></td>
				</tr>
			</table>
		</div>
	</div>
</div>
<div class="admin-comment">
	<p>コメント <%= @post.comments.count %>件</p>

	<%= render "users/posts/comments", post: @post %>

</div>