config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  root 'users/home#top'

  scope module: :users do
  	get 'users/destroy_page'
  	resources :users, only: [:index, :show, :edit, :update], shallow: true do
      resources :relationships, only: [:create, :destroy]
    end
  	resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy], shallow: true do
  		resources :comments, only: [:create, :destroy]
  		resources :likes, only: [:create, :destroy]
  	end
    get 'search' => 'posts#search'
  end

  namespace :admins do
  	resources :users, only: [:index, :destroy]
  	resources :posts, only: [:index, :show, :destroy]
    resources :categories, only: [:new, :create, :update, :destroy]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post

	validates :body, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord

	validates :title, presence: true
	validates :body, presence: true
	validates :category_id, presence: true

	has_many :comments, dependent: :destroy
	has_many :likes, dependent: :destroy
	has_many :post_images, dependent: :destroy
	belongs_to :user
	belongs_to :category

	accepts_attachments_for :post_images, attachment: :image

	def liked_by?(user)
		likes.where(user_id: user.id).exists?
	end

  def self.ranking
    joins(:likes).group(:post_id).order('count(post_id) desc')
  end

	def self.search(keyword, address, category)
		if category == ""
			where(["title like? OR body like?", "%#{keyword}%", "%#{keyword}%"]).where("address like?", "%#{address}%")
		else
			where(category_id: category).where(["title like? OR body like?", "%#{keyword}%", "%#{keyword}%"]).where("address like?", "%#{address}%")
		end
	end
end

app/models/post_image.rb
class PostImage < ApplicationRecord
	belongs_to :post
	attachment :image
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :following, class_name: "User"
	belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :name, length: { maximum: 20 }
  validates :email, presence: true

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id, dependent: :destroy
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :following

  attachment :profile_image
  attachment :cover_image

  def followed_by?(user)
    passive_relationships.where(following_id: user.id).exists?
  end

  def self.ranking
    joins(:passive_relationships).group(:follower_id).order('count(follower_id) desc')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resource)
      case resource
      when Admin
        admins_users_path
      when User
        root_path
      else
        super
      end
    end

  def after_sign_out_path_for(resource)
      case resource
      when Admin, :admin, :admins
        new_admin_session_path
      when User, :user, :users
        root_path
      else
        super
      end
    end

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
	end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admins/categories_helper.rb
module Admins::CategoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/home_helper.rb
module User::HomeHelper
end

app/helpers/user/likes_helper.rb
module User::LikesHelper
end

app/helpers/user/posts_helper.rb
module User::PostsHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ばしょログ</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
  </head>

  <body>
    <% if current_page?(new_admin_session_path) %>

      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <%= link_to new_admin_session_path, class: "navbar-brand navbar-left" do %>
              <%= image_tag "logo.jpg", alt: "サブタイトル", width: "170px" %>
            <% end %>
          </div>
        </div>
      </nav>

    <% else %>
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar_item">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            
            <% if admin_signed_in? %>
              <%= link_to admins_users_path, class: "navbar-brand" do %>
                <%= image_tag "logo.jpg", alt: "サブタイトル", width: "170px" %>
              <% end %>
            <% else %>
              <%= link_to root_path, class: "navbar-brand" do %>
                <%= image_tag "logo3.jpg", alt: "サブタイトル", width: "170px" %>
              <% end %>
              <div class="navbar-brand-center">
                <%= link_to root_path do %>
                  <%= image_tag "logo_3.jpg", alt: "サブタイトル", width: "170px" %>
                <% end %>
              </div>
            <% end %>
          </div>

          <div class="collapse navbar-collapse" id="navbar_item">
            <ul class="nav navbar-nav navbar-right">

              <% if user_signed_in? %>
                <li><%= link_to "マイページ", user_path(current_user.id) %></li>
                <li><%= link_to "記事一覧", posts_path %></li>
                <li><%= link_to "記事投稿", new_post_path %></li>
                <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
              <% elsif admin_signed_in? %>
                <li><%= link_to "会員一覧", admins_users_path %></li>
                <li><%= link_to "記事一覧", admins_posts_path %></li>
                <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "記事一覧", posts_path %></li>
                <li><%= link_to "ログイン", new_user_session_path %></li>
                <li><%= link_to "新規登録", new_user_registration_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    <% end %>

    <div class="container">
      <p id="notice"><%= notice %></p>
      <%= yield %>
    </div>

    <div class="footer">
      <small>© 2020 Copyright Text</small>
    </div>
  </body>
</html>